version: '3.8'
services:
    api:
        build:
            context: .
            target: dev
        command: ['pnpm', 'start:dev']
        env_file:
            - .env
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
            - REDIS_URL=redis://redis:6379
        ports:
            - '3000:3000'
        restart: unless-stopped
        volumes:
            - ./src:/usr/src/api/src # mount src directory for live file system updates
        depends_on:
            -   postgres
            -   redis

    postgres:
        image: postgres:14
        ports:
            - '5432:5432'
        environment:
#            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
#            - POSTGRES_DB=postgres
        restart: unless-stopped
        volumes:
            - pg:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        ports:
            - '6379:6379'
        restart: unless-stopped

volumes:
    pg:
        name: postgres-data
